### ISSUE TITLE
A test method in ArtifactReleaseHistoryScoreTest is failing

### ISSUE THREAD

**Issue by sourabhsparkala** [SAP/fosstars-rating-core#511] opened 2021-04-29 09:12 UTC
There seems to be a bug in Score function or in the Test method. 

Things to do:
- Revaluate Score function to verify if the new generated value is correct.
- If yes, fix the test method.
- If no, check why the test method is failing

**Comment by sourabhsparkala** [comment] 2021-05-04 13:23
The https://github.com/SAP/fosstars-rating-core/blob/master/src/test/java/com/sap/oss/phosphor/fosstars/model/score/oss/ArtifactReleaseHistoryScoreTest.java#L159 expected the value `8.0` instead of `7.6`.

Not sure why, but the same test failed in the Github code CI check as well.

**Comment by mibo** [comment] 2021-05-04 13:37
Just to help me narrow down the root cause, the `@Ignore` was added in PR #504 correct?

**Comment by sourabhsparkala** [comment] 2021-05-04 13:53
> Just to help me narrow down the root cause, the `@Ignore` was added in PR #504 correct?

Yes that is correct. But, please note that the bug was not introduced in PR. @artem-smotrakov I think ran it in his system and he also faced the same issue. Maybe this is OS specific.

**Comment by mibo** [comment] 2021-05-04 14:30
Guess it is not OS specific as the GH action run on Linux/macOS/Windows.
And at least it run during merge of the PR #423 (see https://github.com/SAP/fosstars-rating-core/runs/2226326301) but when I now checkout the commit it fails for me locally.
Somehow strange but maybe some time issue?

As mentioned, will have a l look into.

**Comment by mibo** [comment] 2021-05-04 15:42
The problem was that I was not completely aware of how the `LocalDate(Time).minusMonths()` method works.
This lead to that the `ArtifactReleaseHistoryScoreTest.testTwoMonthOldVersionStable()` was dependent to be executed at the correct month 🙈
Have checked other tests as well and updated those which can be affected as well.
This will be merged as part of PR #505

**Closed** 2021-05-05 09:39 UTC
Labels: bug
